# Generated by Django 3.1.7 on 2021-03-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模型種類')),
            ],
        ),
        migrations.CreateModel(
            name='ModelingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名稱')),
                ('description', models.CharField(max_length=100, verbose_name='模型敘述')),
                ('is_multi_label', models.BooleanField(verbose_name='是否為多標籤')),
                ('jobRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='labeling_jobs.labelingjob')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modeling_jobs.mlmodel')),
            ],
        ),
    ]
