# Generated by Django 3.1.8 on 2021-04-16 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_jobs', '0003_auto_20210415_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名稱')),
                ('description', models.CharField(max_length=100, verbose_name='模型敘述')),
                ('is_multi_label', models.BooleanField(verbose_name='是否為多標籤')),
                ('model_type', models.CharField(choices=[('DUMMY_MODEL', '假模型'), ('SVM_MODEL', 'SVM')], max_length=50)),
                ('job_train_status', models.CharField(blank=True, choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, null=True, verbose_name='模型訓練狀態')),
                ('job_test_status', models.CharField(blank=True, choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, null=True, verbose_name='模型測試狀態')),
                ('model_path', models.CharField(blank=True, max_length=100, verbose_name='模型存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jobRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeling_jobs.labelingjob', verbose_name='使用資料')),
            ],
            options={
                'verbose_name': '模型訓練任務',
                'verbose_name_plural': '模型訓練任務列表',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('train', '訓練資料'), ('dev', '驗證資料'), ('test', '測試資料')], default=None, max_length=10, null=True)),
                ('accuracy', models.FloatField(blank=True, max_length=10, verbose_name='準確率')),
                ('report', models.CharField(max_length=1000, verbose_name='報告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('modeling_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob')),
            ],
        ),
    ]
