# Generated by Django 3.1.7 on 2021-03-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0001_initial'),
        ('modeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='jobRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeling_jobs.labelingjob'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeling_jobs.mlmodel'),
        ),
    ]
