# Generated by Django 3.1.7 on 2021-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingjob',
            name='model_path',
            field=models.CharField(blank=True, max_length=100, verbose_name='模型存放位置'),
        ),
    ]
