# Generated by Django 3.1.7 on 2021-03-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0002_auto_20210326_1740'),
        ('modeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='jobRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeling_jobs.labelingjob'),
        ),
    ]
