# Generated by Django 3.1.8 on 2021-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='model',
            field=models.CharField(choices=[('DUMMY_MODEL', '假模型'), ('SVM_MODEL', 'SVM')], max_length=50, null=True),
        ),
    ]
