# Generated by Django 3.1.8 on 2021-04-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0004_auto_20210420_1000'),
        ('modeling_jobs', '0002_auto_20210420_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '驗證報告', 'verbose_name_plural': '驗證報告列表'},
        ),
        migrations.CreateModel(
            name='EvalPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.document', verbose_name='預測文件')),
                ('ground_truth_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_label', to='labeling_jobs.label', verbose_name='正確標籤')),
                ('prediction_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_label', to='labeling_jobs.label', verbose_name='預測標籤')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.report', verbose_name='驗證報告')),
            ],
            options={
                'verbose_name': '預測結果',
                'verbose_name_plural': '預測結果列表',
            },
        ),
    ]
