# Generated by Django 3.1.7 on 2021-04-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0002_modelingjob_model_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelingjob',
            name='status',
        ),
        migrations.AddField(
            model_name='modelingjob',
            name='job_status',
            field=models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
    ]
