# Generated by Django 3.1.8 on 2021-04-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0002_auto_20210415_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelingjob',
            old_name='model',
            new_name='model_type',
        ),
    ]
