# Generated by Django 3.1.7 on 2021-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0003_auto_20210409_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelingjob',
            old_name='job_status',
            new_name='job_train_status',
        ),
        migrations.AddField(
            model_name='modelingjob',
            name='job_test_status',
            field=models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
    ]
