# Generated by Django 3.1.8 on 2021-04-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0001_initial'),
        ('modeling_jobs', '0003_auto_20210415_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.AlterModelOptions(
            name='modelingjob',
            options={'verbose_name': '模型訓練任務', 'verbose_name_plural': '模型訓練任務列表'},
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='jobRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeling_jobs.labelingjob', verbose_name='使用資料'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='job_test_status',
            field=models.CharField(blank=True, choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, null=True, verbose_name='模型測試狀態'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='job_train_status',
            field=models.CharField(blank=True, choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, null=True, verbose_name='模型訓練狀態'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='model_type',
            field=models.CharField(choices=[('DUMMY_MODEL', '假模型'), ('SVM_MODEL', 'SVM')], max_length=50),
        ),
    ]
