# Generated by Django 3.1.8 on 2021-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0006_remove_uploadfilejob_delimiter'),
        ('modeling_jobs', '0003_auto_20210420_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalprediction',
            name='ground_truth_label',
        ),
        migrations.AddField(
            model_name='evalprediction',
            name='ground_truth_label',
            field=models.ManyToManyField(related_name='ground_truth_label', to='labeling_jobs.Label', verbose_name='正確標籤'),
        ),
        migrations.RemoveField(
            model_name='evalprediction',
            name='prediction_label',
        ),
        migrations.AddField(
            model_name='evalprediction',
            name='prediction_label',
            field=models.ManyToManyField(related_name='prediction_label', to='labeling_jobs.Label', verbose_name='預測標籤'),
        ),
    ]
