# Generated by Django 3.1.13 on 2022-01-26 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingjob',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, null=True, verbose_name='audience api 任務 ID'),
        ),
    ]
