# Generated by Django 3.1.7 on 2021-04-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0004_auto_20210409_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='job_test_status',
            field=models.CharField(blank=True, choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, null=True, verbose_name='任務狀態'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='job_train_status',
            field=models.CharField(blank=True, choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, null=True, verbose_name='任務狀態'),
        ),
    ]
