# Generated by Django 3.1.8 on 2021-04-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0004_auto_20210420_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evalprediction',
            old_name='ground_truth_label',
            new_name='ground_truth_labels',
        ),
        migrations.RenameField(
            model_name='evalprediction',
            old_name='prediction_label',
            new_name='prediction_labels',
        ),
    ]
