# Generated by Django 3.1.7 on 2021-03-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0004_auto_20210331_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='models_ref',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob'),
        ),
    ]
