# Generated by Django 3.1.8 on 2021-04-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0005_auto_20210420_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalprediction',
            name='ground_truth_labels',
        ),
    ]
