# Generated by Django 3.1.13 on 2022-01-26 13:33

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('modeling_jobs', 'ModelingJob')
    for row in MyModel.objects.all():
        row.task_id = uuid.uuid1()
        row.save(update_fields=['task_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0005_modelingjob_task_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
