# Generated by Django 3.1.7 on 2021-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0005_auto_20210331_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingjob',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否已被訓練過'),
        ),
    ]
