# Generated by Django 3.1.13 on 2022-01-26 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0006_auto_20220126_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True, verbose_name='audience api 任務 ID'),
        ),
    ]
