# Generated by Django 3.1.8 on 2021-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0007_auto_20210420_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelingjob',
            name='job_test_status',
        ),
        migrations.AddField(
            model_name='modelingjob',
            name='ext_test_status',
            field=models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='模型測試狀態'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='job_train_status',
            field=models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='模型訓練狀態'),
        ),
    ]
