# Generated by Django 3.1.8 on 2021-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0008_auto_20210420_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingjob',
            name='feature',
            field=models.CharField(choices=[('id', '文章id'), ('s_id', '來源id'), ('s_area_id', '頻道id'), ('title', '標題'), ('author', '作者'), ('content', '內文'), ('post_time', '發文時間')], default='content', max_length=50),
        ),
    ]
