# Generated by Django 3.1.8 on 2021-04-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0009_modelingjob_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelingjob',
            old_name='job_train_status',
            new_name='job_status',
        ),
        migrations.AddField(
            model_name='modelingjob',
            name='error_message',
            field=models.TextField(null=True, verbose_name='錯誤訊息'),
        ),
    ]
