# Generated by Django 3.1.8 on 2021-04-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0010_auto_20210429_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='model_type',
            field=models.CharField(choices=[('DUMMY_MODEL', '假模型'), ('SVM_MODEL', 'SVM'), ('RANDOM_FOREST', '隨機森林')], max_length=50),
        ),
    ]
