# Generated by Django 3.1.8 on 2021-05-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0012_auto_20210503_0938'),
        ('modeling_jobs', '0011_auto_20210429_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='規則內文')),
                ('rule_type', models.CharField(blank=True, max_length=20, verbose_name='規則類型')),
                ('score', models.IntegerField(default=1, verbose_name='命中分數')),
                ('labels', models.ManyToManyField(blank=True, to='labeling_jobs.Label', verbose_name='標籤')),
                ('modeling_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob')),
            ],
        ),
    ]
