# Generated by Django 3.1.8 on 2021-05-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0012_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '模型規則', 'verbose_name_plural': '模型規則列表'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('keyword', '關鍵字'), ('regex', '正則表達式'), ('term_weight', '詞彙加權')], default='keyword', max_length=20, verbose_name='規則類型'),
        ),
    ]
