# Generated by Django 3.1.8 on 2021-05-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0013_auto_20210503_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
