# Generated by Django 3.1.8 on 2021-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0014_delete_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelingjob',
            name='model_type',
        ),
        migrations.AddField(
            model_name='modelingjob',
            name='model_name',
            field=models.CharField(choices=[('DUMMY_MODEL', '假模型'), ('SVM_MODEL', 'SVM'), ('RANDOM_FOREST', '隨機森林'), ('KEYWORD_MODEL', '關鍵字比對')], default='keyword_model', max_length=50),
            preserve_default=False,
        ),
    ]
