# Generated by Django 3.1.8 on 2021-05-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeling_jobs', '0015_auto_20210503_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='feature',
            field=models.CharField(choices=[('id', '文章id'), ('s_id', '來源id'), ('s_area_id', '頻道id'), ('title', '標題'), ('author', '作者'), ('content', '內文'), ('post_time', '發文時間')], default='content', max_length=50, verbose_name='特徵欄位'),
        ),
        migrations.AlterField(
            model_name='modelingjob',
            name='model_name',
            field=models.CharField(choices=[('DUMMY_MODEL', '假模型'), ('SVM_MODEL', 'SVM'), ('RANDOM_FOREST', '隨機森林'), ('KEYWORD_MODEL', '關鍵字比對'), ('REGEX_MODEL', '正則表達式比對'), ('TERM_WEIGHT_MODEL', '關鍵字權重')], max_length=50, verbose_name='模型類型'),
        ),
    ]
