# Generated by Django 3.1.8 on 2021-05-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0030_auto_20210514_1442'),
        ('modeling_jobs', '0016_auto_20210512_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermWeightMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20, verbose_name='詞彙')),
                ('weight', models.FloatField(verbose_name='權重分數')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.label', verbose_name='所屬標籤')),
                ('modeling_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob', verbose_name='模型訓練任務')),
            ],
            options={
                'verbose_name': '詞彙權重',
                'verbose_name_plural': '詞彙權重列表',
                'ordering': ('modeling_job', 'term', 'label'),
                'unique_together': {('modeling_job', 'term', 'label')},
            },
        ),
    ]
