# Generated by Django 3.1.8 on 2021-05-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0030_auto_20210514_1442'),
        ('modeling_jobs', '0017_termweightmeta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermWeightMeta',
            new_name='TermWeight',
        ),
    ]
