# Generated by Django 3.1.11 on 2021-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0019_auto_20210528_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelingjob',
            name='is_multi_label',
            field=models.BooleanField(default=False, verbose_name='是否為多標籤'),
        ),
    ]
