# Generated by Django 3.1.11 on 2021-06-11 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeling_jobs', '0020_auto_20210609_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModelJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_files', verbose_name='檔案')),
                ('job_status', models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modeling_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob', verbose_name='所屬任務')),
            ],
            options={
                'verbose_name': '模型上傳任務',
                'verbose_name_plural': '模型上傳任務列表',
            },
        ),
    ]
