# Generated by Django 3.1.8 on 2021-06-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0021_uploadmodeljob'),
        ('modeling_jobs', '0020_auto_20210603_1611'),
    ]

    operations = [
    ]
