# Generated by Django 3.1.7 on 2021-03-29 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling_jobs', '0002_auto_20210326_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='預測工作名稱')),
                ('description', models.TextField(verbose_name='定義與說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更改')),
                ('job_status', models.CharField(default='wait', max_length=20, verbose_name='任務狀態')),
                ('apply_models', models.ManyToManyField(blank=True, to='modeling_jobs.ModelingJob', verbose_name='使用模型列表')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '預測任務',
                'verbose_name_plural': '預測任務列表',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='來源名稱')),
                ('s_area_id', models.CharField(max_length=100, verbose_name='opv_id')),
                ('description', models.TextField(verbose_name='定義與說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更改')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '資料源',
                'verbose_name_plural': '資料源列表',
            },
        ),
        migrations.CreateModel(
            name='PredictingTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='預測目標名稱')),
                ('description', models.TextField(verbose_name='定義與說明')),
                ('begin_post_time', models.DateTimeField(verbose_name='起始發文時間')),
                ('end_post_time', models.DateTimeField(verbose_name='結束發文時間')),
                ('min_content_length', models.IntegerField(default=10, verbose_name='最小文章長度')),
                ('max_content_length', models.IntegerField(default=2000, verbose_name='最大文章長度')),
                ('predicting_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predicting_jobs.predictingjob', verbose_name='預測任務')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predicting_jobs.source', verbose_name='預測資料源')),
            ],
            options={
                'verbose_name': '預測範圍',
                'verbose_name_plural': '預測範圍列表',
            },
        ),
    ]
