# Generated by Django 3.1.7 on 2021-03-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeling_jobs', '0001_initial'),
        ('predicting_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingtask',
            name='apply_models',
            field=models.ManyToManyField(blank=True, to='modeling_jobs.ModelingJob', verbose_name='使用模型列表'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='來源名稱')),
                ('s_area_id', models.CharField(max_length=100, verbose_name='opv_id')),
                ('description', models.TextField(verbose_name='定義與說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更改')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='predictingtask',
            name='apply_sources',
            field=models.ManyToManyField(blank=True, to='predicting_jobs.Source', verbose_name='預測資料源列表'),
        ),
    ]
