# Generated by Django 3.1.8 on 2021-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictingresult',
            name='label',
        ),
        migrations.AddField(
            model_name='predictingresult',
            name='label_name',
            field=models.CharField(default='1', max_length=200, verbose_name='標籤名稱'),
            preserve_default=False,
        ),
    ]
