# Generated by Django 3.1.13 on 2021-08-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictingjob',
            name='job_status',
            field=models.CharField(choices=[('created', '已建立'), ('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
        migrations.AlterField(
            model_name='predictingtarget',
            name='job_status',
            field=models.CharField(choices=[('created', '已建立'), ('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
    ]
