# Generated by Django 3.1.7 on 2021-03-25 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modeling_jobs', '0001_initial'),
        ('predicting_jobs', '0002_auto_20210325_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictingTask',
            new_name='PredictingJob',
        ),
    ]
