# Generated by Django 3.1.8 on 2021-04-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0002_auto_20210422_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='port',
            field=models.IntegerField(default=3306, verbose_name='資料庫連接埠'),
        ),
    ]
