# Generated by Django 3.1.7 on 2021-03-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0002_auto_20210326_1740'),
        ('predicting_jobs', '0003_auto_20210330_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyingmodel',
            name='modeling_jobs',
        ),
        migrations.RemoveField(
            model_name='applyingmodel',
            name='predicting_jobs',
        ),
        migrations.AddField(
            model_name='applyingmodel',
            name='modeling_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob', verbose_name='使用模型列表'),
        ),
        migrations.AddField(
            model_name='applyingmodel',
            name='predicting_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predicting_jobs.predictingjob'),
        ),
    ]
