# Generated by Django 3.1.8 on 2021-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0003_auto_20210426_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingresult',
            name='feature_content',
            field=models.TextField(blank=True, verbose_name='特徵內容'),
        ),
    ]
