# Generated by Django 3.1.7 on 2021-03-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0003_auto_20210325_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictingjob',
            options={'verbose_name': '預測任務', 'verbose_name_plural': '預測任務列表'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': '資料源', 'verbose_name_plural': '資料源列表'},
        ),
    ]
