# Generated by Django 3.1.8 on 2021-04-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0004_predictingresult_feature_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictingresult',
            name='feature_content',
        ),
    ]
