# Generated by Django 3.1.7 on 2021-03-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0002_auto_20210326_1740'),
        ('predicting_jobs', '0004_auto_20210330_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyingmodel',
            name='modeling_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modeling_jobs.modelingjob', unique=True, verbose_name='應用模型任務'),
        ),
    ]
