# Generated by Django 3.1.8 on 2021-04-27 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0006_predictingresult_apply_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
    ]
