# Generated by Django 3.1.7 on 2021-03-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0002_auto_20210326_1740'),
        ('predicting_jobs', '0006_auto_20210330_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applyingmodel',
            unique_together={('predicting_job', 'modeling_job')},
        ),
    ]
