# Generated by Django 3.1.7 on 2021-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0007_auto_20210330_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictingjob',
            name='job_status',
            field=models.CharField(choices=[('wait', 'Wait'), ('processing', 'Processing'), ('break', 'Break'), ('error', 'Error'), ('done', 'Done')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
    ]
