# Generated by Django 3.1.8 on 2021-04-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0007_predictingresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingresult',
            name='source_author',
            field=models.CharField(default='UNK', max_length=200, verbose_name='作者'),
        ),
    ]
