# Generated by Django 3.1.7 on 2021-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0008_auto_20210330_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictingjob',
            name='job_status',
            field=models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
    ]
