# Generated by Django 3.1.8 on 2021-04-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0008_predictingresult_source_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingtarget',
            name='error_message',
            field=models.TextField(null=True, verbose_name='錯誤訊息'),
        ),
    ]
