# Generated by Django 3.1.8 on 2021-05-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0009_predictingtarget_error_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyingmodel',
            options={'ordering': ('priority', 'created_at'), 'verbose_name': '應用模型', 'verbose_name_plural': '應用模型列表'},
        ),
    ]
