# Generated by Django 3.1.8 on 2021-05-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0010_auto_20210512_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyingmodel',
            name='predicting_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predicting_jobs.predictingjob', verbose_name='族群貼標任務'),
        ),
        migrations.AlterField(
            model_name='applyingmodel',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='predictingtarget',
            name='begin_post_time',
            field=models.DateField(verbose_name='起始發文時間'),
        ),
        migrations.AlterField(
            model_name='predictingtarget',
            name='end_post_time',
            field=models.DateField(verbose_name='結束發文時間'),
        ),
    ]
