# Generated by Django 3.1.8 on 2021-06-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling_jobs', '0023_auto_20210625_1544'),
        ('predicting_jobs', '0011_auto_20210528_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictingresult',
            options={'ordering': ('id',), 'verbose_name': '預測結果', 'verbose_name_plural': '預測結果列表'},
        ),
        migrations.RemoveField(
            model_name='predictingresult',
            name='apply_path',
        ),
        migrations.AddField(
            model_name='predictingresult',
            name='applied_content',
            field=models.TextField(null=True, verbose_name='命中內容'),
        ),
        migrations.AddField(
            model_name='predictingresult',
            name='applied_meta',
            field=models.JSONField(null=True, verbose_name='預測細節'),
        ),
        migrations.AddField(
            model_name='predictingresult',
            name='applied_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='modeling_jobs.modelingjob', verbose_name='命中模型'),
        ),
    ]
