# Generated by Django 3.1.8 on 2021-06-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0012_auto_20210625_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictingresult',
            name='score',
        ),
    ]
