# Generated by Django 3.1.8 on 2021-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0013_remove_predictingresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingresult',
            name='applied_feature',
            field=models.CharField(choices=[('id', '文章id'), ('s_id', '來源'), ('s_area_id', '來源網站'), ('title', '標題'), ('author', '作者'), ('content', '內文'), ('post_time', '發文時間')], default='content', max_length=50, verbose_name='特徵欄位'),
        ),
    ]
