# Generated by Django 3.1.8 on 2021-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0014_predictingresult_applied_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictingtarget',
            name='task_id',
            field=models.UUIDField(default=None, null=True, verbose_name='排程任務id'),
        ),
    ]
