# Generated by Django 3.1.8 on 2021-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicting_jobs', '0015_predictingtarget_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictingjob',
            name='job_status',
            field=models.CharField(choices=[('created', 'ˇ已建立'), ('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
        migrations.AlterField(
            model_name='predictingtarget',
            name='job_status',
            field=models.CharField(choices=[('created', 'ˇ已建立'), ('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態'),
        ),
        migrations.AlterField(
            model_name='predictingtarget',
            name='task_id',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='排程任務id'),
        ),
    ]
