# Generated by Django 3.1.7 on 2021-03-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='標題')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('s_area_id', models.CharField(max_length=100, verbose_name='頻道id')),
                ('content', models.TextField(verbose_name='內文')),
                ('post_time', models.DateTimeField(verbose_name='發布時間')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='標記工作名稱')),
                ('description', models.TextField(verbose_name='定義與說明')),
                ('create_date', models.DateTimeField(verbose_name='建立時間')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='標籤名稱')),
                ('description', models.TextField(verbose_name='標籤定義')),
                ('documents', models.ManyToManyField(to='labeling_jobs.Document')),
                ('labeling_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='labeling_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.job'),
        ),
    ]
