# Generated by Django 3.1.13 on 2021-07-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilejob',
            old_name='job',
            new_name='labeling_job',
        ),
    ]
