# Generated by Django 3.1.8 on 2021-07-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='labeling_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='labeling_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='uploadfilejob',
            old_name='labeling_job',
            new_name='job',
        ),
    ]
