# Generated by Django 3.1.7 on 2021-03-26 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='內文'),
        ),
        migrations.AlterField(
            model_name='document',
            name='post_time',
            field=models.DateTimeField(blank=True, verbose_name='發布時間'),
        ),
        migrations.AlterField(
            model_name='document',
            name='s_area_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='頻道id'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=512, verbose_name='標題'),
        ),
        migrations.AlterField(
            model_name='labelingjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labelingjob',
            name='name',
            field=models.CharField(max_length=100, verbose_name='標記工作名稱'),
        ),
    ]
