# Generated by Django 3.1.8 on 2021-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilejob',
            name='delimiter',
            field=models.CharField(choices=[(',', '逗號'), ('\t', '制表符')], default=',', max_length=1, verbose_name='分隔符號'),
        ),
    ]
