# Generated by Django 3.1.8 on 2021-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('訓練資料', 'Train'), ('驗證資料', 'Dev'), ('測試資料', 'Test')], default=None, max_length=10, null=True),
        ),
    ]
