# Generated by Django 3.1.8 on 2021-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0002_uploadfilejob_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilejob',
            name='delimiter',
            field=models.CharField(choices=[(',', 'Comma'), ('\t', 'Tab')], default=',', max_length=1, verbose_name='分隔符號'),
        ),
    ]
