# Generated by Django 3.1.7 on 2021-03-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0002_auto_20210326_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='雜湊值'),
        ),
    ]
