# Generated by Django 3.1.8 on 2021-07-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0002_auto_20210713_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='job',
            new_name='labeling_job',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='job',
            new_name='labeling_job',
        ),
        migrations.RenameField(
            model_name='uploadfilejob',
            old_name='job',
            new_name='labeling_job',
        ),
    ]
