# Generated by Django 3.1.8 on 2021-04-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0003_auto_20210415_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('train', '訓練資料'), ('dev', '驗證資料'), ('test', '測試資料'), ('ext_test', '額外測試資料')], default=None, max_length=10, null=True),
        ),
    ]
