# Generated by Django 3.1.7 on 2021-03-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0002_auto_20210326_1740'),
        ('labeling_jobs', '0003_document_hash_num'),
    ]

    operations = [
    ]
