# Generated by Django 3.1.7 on 2021-03-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0003_auto_20210316_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='labeling_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='labeling_job',
            new_name='job',
        ),
    ]
