# Generated by Django 3.1.7 on 2021-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0004_auto_20210316_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(to='labeling_jobs.Label'),
        ),
    ]
