# Generated by Django 3.1.8 on 2021-07-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0004_auto_20210714_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='labeling_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='uploadfilejob',
            old_name='labeling_job',
            new_name='job',
        ),
    ]
