# Generated by Django 3.1.8 on 2021-04-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0005_auto_20210420_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilejob',
            name='delimiter',
        ),
    ]
