# Generated by Django 3.1.7 on 2021-04-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0005_auto_20210330_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='檔案名稱')),
                ('description', models.TextField(blank=True, verbose_name='檔案描述')),
                ('file_path', models.FileField(upload_to='upload_files', verbose_name='檔案位置')),
                ('job_status', models.CharField(choices=[('wait', '等待中'), ('processing', '處理中'), ('break', '中斷'), ('error', '錯誤'), ('done', '完成')], default='wait', max_length=20, verbose_name='任務狀態')),
                ('labeling_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.labelingjob', verbose_name='所屬任務')),
            ],
        ),
    ]
