# Generated by Django 3.1.7 on 2021-03-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_jobs', '0006_auto_20210316_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='label_created_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='label_updated_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
