# Generated by Django 3.1.8 on 2021-07-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0006_auto_20210714_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='labeling_job',
            new_name='job',
        ),
    ]
