# Generated by Django 3.1.7 on 2021-04-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0006_uploadfilejob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilejob',
            old_name='file_path',
            new_name='file',
        ),
    ]
