# Generated by Django 3.1.8 on 2021-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0007_auto_20210420_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='human_labels',
        ),
        migrations.AlterField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(blank=True, to='labeling_jobs.Label', verbose_name='正確標籤'),
        ),
    ]
