# Generated by Django 3.1.7 on 2021-04-01 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_jobs', '0007_auto_20210401_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilejob',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uploadfilejob',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadfilejob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfilejob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadfilejob',
            name='file',
            field=models.FileField(upload_to='upload_files', verbose_name='檔案'),
        ),
    ]
