# Generated by Django 3.1.8 on 2021-04-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0008_auto_20210420_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='來源id'),
        ),
    ]
