# Generated by Django 3.1.7 on 2021-03-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0009_auto_20210317_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='label',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='label',
            name='updated_by',
        ),
    ]
