# Generated by Django 3.1.8 on 2021-04-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0009_document_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingjob',
            name='job_type',
            field=models.CharField(choices=[('supervise_model', '監督式學習模型'), ('rule_base', '規則模型'), ('term_weight', '詞彙權重模型')], default='supervise_model', max_length=20, verbose_name='任務類型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labelingjob',
            name='name',
            field=models.CharField(default='supervise_model', max_length=100, verbose_name='標記工作名稱'),
        ),
    ]
