# Generated by Django 3.1.8 on 2021-04-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0010_auto_20210429_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelingjob',
            old_name='job_type',
            new_name='job_data_type',
        ),
    ]
