# Generated by Django 3.1.8 on 2021-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0011_auto_20210429_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfilejob',
            options={'verbose_name': '文件上傳任務', 'verbose_name_plural': '文件上傳任務列表'},
        ),
        migrations.AlterField(
            model_name='labelingjob',
            name='job_data_type',
            field=models.CharField(choices=[('supervise_model', '監督式學習模型'), ('rule_base', '規則模型'), ('term_weight', '詞彙權重模型')], default='supervise_model', max_length=20, verbose_name='任務類型'),
        ),
        migrations.AlterField(
            model_name='labelingjob',
            name='name',
            field=models.CharField(default='Job', max_length=100, verbose_name='標記工作名稱'),
        ),
    ]
