# Generated by Django 3.1.7 on 2021-03-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0011_auto_20210317_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_multi_label',
            field=models.BooleanField(default=False, verbose_name='是否屬於多標籤'),
        ),
    ]
