# Generated by Django 3.1.8 on 2021-05-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0012_auto_20210503_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingjob',
            name='job_data_type',
        ),
    ]
