# Generated by Django 3.1.8 on 2021-05-03 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0013_remove_labelingjob_job_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingjob',
            name='job_data_type',
            field=models.CharField(choices=[('supervise_model', '監督式學習模型'), ('rule_base', '規則模型'), ('term_weight', '詞彙權重模型')], default='supervise_model', max_length=20, verbose_name='任務類型'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='規則內文')),
                ('rule_type', models.CharField(choices=[('keyword', '關鍵字'), ('regex', '正則表達式'), ('term_weight', '詞彙加權')], default='keyword', max_length=20, verbose_name='規則類型')),
                ('score', models.IntegerField(default=1, verbose_name='命中分數')),
                ('labeling_job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.labelingjob')),
                ('labels', models.ManyToManyField(blank=True, to='labeling_jobs.Label', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '規則',
                'verbose_name_plural': '規則列表',
            },
        ),
    ]
