# Generated by Django 3.1.8 on 2021-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0014_auto_20210503_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='labels',
            field=models.ManyToManyField(to='labeling_jobs.Label', verbose_name='標籤'),
        ),
    ]
