# Generated by Django 3.1.8 on 2021-05-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0016_auto_20210503_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='content',
            field=models.CharField(max_length=200, verbose_name='規則內文'),
        ),
    ]
