# Generated by Django 3.1.8 on 2021-05-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0019_auto_20210503_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='labeling_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.labelingjob'),
        ),
        migrations.RemoveField(
            model_name='rule',
            name='labels',
        ),
        migrations.AddField(
            model_name='rule',
            name='labels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labeling_jobs.label', verbose_name='標籤'),
            preserve_default=False,
        ),
    ]
