# Generated by Django 3.1.8 on 2021-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0020_auto_20210503_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='score',
            field=models.FloatField(default=1, verbose_name='命中分數'),
        ),
    ]
