# Generated by Django 3.1.8 on 2021-05-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0021_auto_20210503_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='labels',
            new_name='label',
        ),
    ]
