# Generated by Django 3.1.8 on 2021-05-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0024_auto_20210512_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('content', 'match_type')},
        ),
    ]
