# Generated by Django 3.1.8 on 2021-05-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0026_auto_20210512_1807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('content', 'match_type')},
        ),
    ]
