# Generated by Django 3.1.8 on 2021-05-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0029_auto_20210513_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingjob',
            name='job_data_type',
            field=models.CharField(choices=[('supervise_model', '監督式學習模型'), ('rule_base', '關鍵字規則模型'), ('regex', '正則表達式模型'), ('term_weight', '詞彙權重模型')], default='supervise_model', max_length=20, verbose_name='任務類型'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='match_type',
            field=models.CharField(choices=[('start', '比對開頭'), ('end', '比對結尾'), ('exactly', '完全一致'), ('partially', '部分吻合')], default='partially', max_length=20, verbose_name='比對方式'),
        ),
    ]
