# Generated by Django 3.1.11 on 2021-06-01 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labeling_jobs', '0031_auto_20210528_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Job', max_length=100, verbose_name='範例資料名稱')),
                ('description', models.TextField(verbose_name='定義與說明')),
                ('job_data_type', models.CharField(choices=[('supervise_model', '監督式學習模型'), ('rule_base', '關鍵字規則模型'), ('regex', '正則表達式模型'), ('term_weight', '詞彙權重模型')], default=None, max_length=20, null=True, verbose_name='任務類型')),
                ('file', models.FileField(upload_to='sample_data_files', verbose_name='檔案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '範例資料',
                'verbose_name_plural': '範例資料列表',
                'ordering': ('created_at', 'name', 'job_data_type'),
            },
        ),
    ]
