# Generated by Django 3.1.11 on 2021-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_jobs', '0032_sampledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='name',
            field=models.CharField(default='Sample Data', max_length=100, verbose_name='範例資料名稱'),
        ),
    ]
