# Generated by Django 3.1.13 on 2022-04-25 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documenting_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentingjob',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True, verbose_name='audience api 任務 ID'),
        ),
    ]
