# Generated by Django 3.1.13 on 2022-05-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenting_jobs', '0002_documentingjob_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentingjob',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='documentingjob',
            name='is_multi_label',
        ),
        migrations.RemoveField(
            model_name='documentingjob',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='documentingjob',
            name='update_time',
        ),
    ]
