# Generated by Django 3.1.13 on 2022-05-05 13:56

from django.db import migrations, models
import documenting_jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('documenting_jobs', '0003_auto_20220505_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentingjob',
            name='task_id',
            field=models.UUIDField(default=documenting_jobs.models.hex_uuid, editable=False, unique=True, verbose_name='audience api 任務 ID'),
        ),
    ]
